<?php
/**
 * Created by PhpStorm.
 * User: mahdynasr
 * Date: 03/04/18
 */

/** @var \MahdyNasr\Newsletter\Block\Subscribe $block */
if ($this->isAllowable()) :
?>


<div class="block mahdy-newsletter">

    <div class="header">
        <strong id="title" ><?= $block->escapeHtml(__('Newsletter')) ?></strong>
        <strong id="newsletter-close">X</strong>
    </div>
    <div class="content">
        <form class="form mahdy-subscribe"
              novalidate
              action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="mahdy-newsletter-validate-detail">

            <div class="fieldset">
                <div class="field mahdy-newsletter">
                    <label class="label"
                           for="mahdy-newsletter_name"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
                    <div class="mahdy-control control-name">
                        <input name="name" type="text" id="mahdy-newsletter_name"
                               placeholder="<?= $block->escapeHtmlAttr(__('Enter your first name')) ?>"/>
                    </div>
                </div>
                <div class="field mahdy-newsletter">
                    <label class="label"
                           for="mahdy-newsletter"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
                    <div class="mahdy-control control-email">
                        <input name="email" type="email" id="mahdy-newsletter"
                               placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
                               data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="mahdy-actions">
                    <button class="mahdy-action mahdy-subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                            type="submit">
                        <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                    </button>
                </div>
            </div>


        </form>
    </div>
</div>
<?php endif;?>
